import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'
import Layout from '../components/layoutSecond'
import { useState } from "react";

const Home: NextPage = () => {
  const [count, setCount] = useState(0)
  const increaseCount = () => {
    setCount(count + 1)
    console.log('---', count)
    setTimeout(()=>{
      console.log('setTimeout---', count)
    }, 100)
  }
  return (
    <div className={styles.container}>
      <div>
        <p>Your count is {count}</p>
        <button onClick={increaseCount}>+</button>
      </div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}> 
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
        <Layout>
          <Link href="/common/test?foo=bar">
            <a>Go to pages/post/[pid].js</a>
          </Link>
        </Layout>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.tsx</code>
        </p>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
